sclad/Models/Punkt.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace sclad.Models
{
    public class Punkt
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Наименование Пункта")]
        [Required(ErrorMessage = "Это обязательное поле")]
        public string Name  { get; set; }
        [DisplayName("Адресс Пункта")]
        [Required(ErrorMessage = "Это обязательное поле")]
        public string Adress { get; set; }
        [DisplayName("Контакты Пункта")]
        [Required(ErrorMessage = "Это обязательное поле")]
        public string Kontakti { get; set; }
    }
}

sclad/Controllers/PunktController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using sclad.Data;
using sclad.Models;
using System.Data;

namespace sclad.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class PunktController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PunktController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Punkt> objList = _db.Punkt;
            return View(objList);
        }
        //GET-CREATE
        public IActionResult Create()
        {
            
            return View();
        }
        //POST-CREATE
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult Create(Punkt obj)
        {
            _db.Punkt.Add(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Пункт создан успешно!";
            return RedirectToAction("Index");
        }

        //GET-EDIT
        public IActionResult Edit(int? Id)
        {
            if (Id == null) { return NotFound(); }
            var obj = _db.Punkt.Find(Id);
            if (obj == null) { return NotFound(); }
            return View(obj);
        }

        //POST-EDIT
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult Edit(Punkt obj)
        {
            _db.Punkt.Update(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Пункт изменён успешно!";
            return RedirectToAction("Index");
        }

        //GET-DELETE
        public IActionResult Delete(int? Id)
        {
            if (Id == null) { return NotFound(); }
            var obj = _db.Punkt.Find(Id);
            if (obj == null) { return NotFound(); }
            return View(obj);
        }


        //POST-DELITE
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult DeletePost(int? Id)
        {
            var obj = _db.Punkt.Find(Id);
            if (obj == null) { return NotFound(); }
            _db.Punkt.Remove(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Пункт удалён успешно!";
            return RedirectToAction("Index");
        }
    }
}

sclad/Views/Punkt/Create.cshtml
@model sclad.Models.Punkt
<form method="post" asp-action="Create">
    <div class="border p-3">

        <div class="mb-3 row">
            <h2 class="text-info pl-3"> ADD Punkt</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Adress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Adress" class="form-control" />
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Kontakti"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Kontakti" class="form-control" />
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Создать"/>
                        </div>
                        <div class="col">
                            <a asp-controller="Punkt" asp-action="Index" class="btn btn-success w-100">
                                Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

sclad/Views/Punkt/Delete.cshtml
@model sclad.Models.Punkt
<form method="post" asp-action="DeletePost">
    <div class="border p-3">
        <input asp-for="Id" hidden />
        <div class="mb-3 row">
            <h2 class="text-info pl-3"> Delete Punkt</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />

                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Adress"></label>
                    </div>
                    <div class="col-8">
                        <input disabled asp-for="Adress" class="form-control" />

                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Kontakti"></label>
                    </div>
                    <div class="col-8">
                        <input disabled asp-for="Kontakti" class="form-control" />

                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Удалить" />
                        </div>
                        <div class="col">
                            <a asp-controller="Punkt" asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

sclad/Views/Punkt/Edit.cshtml
@model sclad.Models.Punkt
<form method="post" asp-action="Edit">
    <div class="border p-3">
        <input asp-for="Id" hidden />
        <div class="mb-3 row">
            <h2 class="text-info pl-3"> Edit Punkt</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Adress"></label>
                    </div>
                    <div class="col-8">
                        <input  asp-for="Adress" class="form-control" />
                        <span asp-validation-for="Adress" class="text-danger"></span>
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Kontakti"></label>
                    </div>
                    <div class="col-8">
                        <input  asp-for="Kontakti" class="form-control" />
                        <span asp-validation-for="Kontakti" class="text-danger"></span>
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Обновить" />
                        </div>
                        <div class="col">
                            <a asp-controller="Punkt" asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
    
}

sclad/Views/Punkt/Index.cshtml
@model IEnumerable<sclad.Models.Punkt>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Punkt List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Punkt" asp-action="Create" class="btn btn-primary">
                <i class="fa-sharp fa-solid fa-plus fa-beat"></i> &nbsp; Create new Punkt
            </a>

        </div>
    </div>
    <br /><br />
    @if (Model.Count() > 0)
    {
        <table class=" table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Наименование 
                    </th>
                    <th>
                        Адресс 
                    </th>
                    <th>
                        Контакты
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="30%">@obj.Name</td>
                        <td width="30%">@obj.Adress</td>
                        <td width="20%">@obj.Kontakti</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Punkt" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary ">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="Punkt" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger ">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Punkts exists.</p>
    }
</div>