sclad/Controllers/ItemTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using sclad.Data;
using sclad.Models;
using System.Data;

namespace sclad.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ItemTypeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ItemTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<ItemType> objList = _db.ItemType;
            return View(objList);
        }
        //GET-CREATE
        public IActionResult Create()
        {
            
            return View();
        }
        //POST-CREATE
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult Create(ItemType obj)
        {
            _db.ItemType.Add(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Тип создан успешно!";
            return RedirectToAction("Index");
        }

        //GET-EDIT
        public IActionResult Edit(int? Id)
        {
            if(Id == null) { return NotFound(); }
            var obj = _db.ItemType.Find(Id);
            if(obj == null) { return NotFound(); }
            return View(obj);
        }

        //POST-EDIT
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult Edit(ItemType obj)
        {
            _db.ItemType.Update(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Тип изменён успешно!";
            return RedirectToAction("Index");
        }

        //GET-DELETE
        public IActionResult Delete(int? Id)
        {
            if (Id == null) { return NotFound(); }
            var obj = _db.ItemType.Find(Id);
            if (obj == null) { return NotFound(); }
            return View(obj);
        }


        //POST-DELITE
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult DeletePost(int? Id)
        {
            var obj = _db.ItemType.Find(Id);
            if (obj == null) { return NotFound(); }
            _db.ItemType.Remove(obj);
            _db.SaveChanges();
            TempData[WC.Success] = "Тип удалён успешно!";
            return RedirectToAction("Index");
        }
    }
}

sclad/Views/ItemType/Create.cshtml
@model sclad.Models.ItemType
<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="mb-3 row">
            <h2 class="text-info pl-3"> ADD ItemType</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Unit"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Unit" class="form-control" />
                        <span asp-validation-for="Unit" class="text-danger"></span>
                    </div>

                </div>
                
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Создать"/>
                        </div>
                        <div class="col">
                            <a asp-controller="ItemType" asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{

    @{<partial name="_ValidationScriptsPartial"/>}

}

sclad/Views/ItemType/Delete.cshtml
@model sclad.Models.ItemType
<form method="post" asp-action="DeletePost">
    <div class="border p-3">
        <input asp-for="Id" hidden />
        <div class="mb-3 row">
            <h2 class="text-info pl-3"> Delete ItemType</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />

                    </div>

                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Unit"></label>
                    </div>
                    <div class="col-8">
                        <input  disabled asp-for="Unit" class="form-control" />

                    </div>

                </div>
                
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Удалить" />
                        </div>
                        <div class="col">
                            <a asp-controller="ItemType" asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

sclad/Views/ItemType/Edit.cshtml
@model sclad.Models.ItemType
<form method="post" asp-action="Edit">
    <div class="border p-3">
        <input asp-for="Id" hidden />
        <div class="mb-3 row">
            <h2 class="text-info pl-3"> Edit ItemType</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="mb-3 row">
                    <div class="col-4">
                        <label asp-for="Unit"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Unit" class="form-control" />
                        <span asp-validation-for="Unit" class="text-danger"></span>
                    </div>

                </div>
                
                <div class="mb-3 row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Обновить" />
                        </div>
                        <div class="col">
                            <a asp-controller="ItemType" asp-action="Index" class="btn btn-success w-100">
                                <i class="fa-solid fa-right-from-bracket"></i> &nbsp; Назад
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
    
}

sclad/Views/ItemType/Index.cshtml
@model IEnumerable<sclad.Models.ItemType>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Item Type List</h2>
        </div>
        <div class="col-6 text-end" >
            <a asp-controller="ItemType" asp-action="Create" class="btn btn-primary">
                <i class="fa-sharp fa-solid fa-plus fa-beat"></i> &nbsp; Create new Item Type
            </a>
            
        </div>
    </div>
    <br /><br />
    @if (Model.Count()>0)
    {
        <table class=" table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Item Type Name
                    </th>
                    <th>
                        Unit
                    </th>
                    <th>
                        Price
                    </th>
                    
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model)
                {
                    <tr>
                        <td width="50%">@obj.Name</td>
                        <td width="30%">@obj.Unit</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ItemType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary ">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a asp-controller="ItemType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger ">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Item Type exists.</p>
    }
</div>