sclad/Controllers/CartController.cs
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using sclad.Data;
using sclad.Models;
using sclad.Models.ViewModels;
using sclad.Utility;
using sclad.Utility.BrainTree;
using System.Security.Claims;
using System.Text;

namespace sclad.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private IEmailSender _emailSender;
        private IBrainTreeGate _brain;
        [BindProperty]
        public ItemUserVM ItemUserVM { get; set; }
        public CartController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender,IBrainTreeGate brain)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _brain = brain;
        }
        public IActionResult Index()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if(HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0 &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count()!=null)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> itemInCart = shoppingCartList.Select(i=>i.ItemId).ToList();
            IEnumerable<Item> itemListTemp = _db.Item.Where(u=>itemInCart.Contains(u.Id));
            IList<Item> itemList = new List<Item>();
            
            foreach(var item in shoppingCartList)
            {
                Item itemTemp= itemListTemp.FirstOrDefault(u=> u.Id == item.ItemId);
                itemTemp.TempKol = item.Kol;
                itemList.Add(itemTemp);
            }
            foreach (var obj in itemList)
            {
                obj.ItemType = _db.ItemType.FirstOrDefault(u => u.Id == obj.ItemTypeId);
                obj.Punkt = _db.Punkt.FirstOrDefault(u => u.Id == obj.PunktId);
            }
            return View(itemList);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Item> ItemList)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            foreach (Item item in ItemList)
            {
                shoppingCartList.Add(new ShoppingCart { ItemId = item.Id, Kol = item.TempKol });
            }
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);
            
            return RedirectToAction(nameof(Summary));
        }




        //GET-SUMMARY
        public IActionResult Summary()
        {

            var gateway = _brain.GetGateway();
            var clientToken = gateway.ClientToken.Generate();
            ViewBag.ClientToken = clientToken;





            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);



            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0 &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() != null)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> itemInCart = shoppingCartList.Select(i => i.ItemId).ToList();
            IEnumerable<Item> itemList = _db.Item.Where(u => itemInCart.Contains(u.Id));
            foreach (var obj in itemList)
            {
                obj.ItemType = _db.ItemType.FirstOrDefault(u => u.Id == obj.ItemTypeId);
                obj.Punkt = _db.Punkt.FirstOrDefault(u => u.Id == obj.PunktId);
            }

            ItemUserVM = new ItemUserVM()
            {
                ApplicationUser = _db.ApplicationUser.FirstOrDefault(u => u.Id == claim.Value)
            };

            foreach(var cartobj in shoppingCartList) 
            {
                Item ItemTemp = _db.Item.FirstOrDefault(u => u.Id == cartobj.ItemId);
                ItemTemp.TempKol = cartobj.Kol;
                ItemUserVM.ItemList.Add(ItemTemp);
            }

            return View(ItemUserVM);
        }




        //POST-SUMMARY
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(/*ItemUserVM temUserVM*/IFormCollection collection)//так как есть атрибут [BindProperty] оно доступно и так
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


            
            //чето
            decimal orderTotal = 0;
            foreach(Item item in ItemUserVM.ItemList)
            {
                orderTotal += item.Price * item.TempKol;
            }
            OrderHeader orderHeader = new OrderHeader()
            {
                CreatedByUserId = claim.Value,
                FinalOrderTotal = orderTotal,
                City=ItemUserVM.ApplicationUser.City,
                StreetAddress = ItemUserVM.ApplicationUser.StreetAdress,
                State = ItemUserVM.ApplicationUser.State,
                PostalCode = ItemUserVM.ApplicationUser.PostalCode,
                FullName = ItemUserVM.ApplicationUser.FullName,
                Email = ItemUserVM.ApplicationUser.Email,
                PhoneNumber = ItemUserVM.ApplicationUser.PhoneNumber,
                OrderDate = DateTime.Now,
                OrderStatus = WC.StatusPending
            };
            _db.OrderHeader.Add(orderHeader);
            _db.SaveChanges();

            foreach(var item in ItemUserVM.ItemList)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderHeaderId = orderHeader.Id,
                    PricePerKol = item.Price,
                    Kol = item.TempKol,
                    ItemId = item.Id
                };
                _db.OrderDetail.Add(orderDetail);
            }
            _db.SaveChanges();

            string nonceFromTheClient = collection["payment_method_nonce"];

            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(orderHeader.FinalOrderTotal),
                PaymentMethodNonce = nonceFromTheClient,
                OrderId = orderHeader.Id.ToString(),
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };
            var gateway = _brain.GetGateway();
            Result<Transaction> result = gateway.Transaction.Sale(request);

            if(result.Target.ProcessorResponseText == "Approved")
            {
                orderHeader.TransactionId = result.Target.Id;
                orderHeader.OrderStatus = WC.StatusApproved;
            }
            else
            {
                orderHeader.OrderStatus = WC.StatusCancelled;
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(InquiryConfirmation), new {id = orderHeader.Id});



            //чето кончилось



            var PathToTemplate = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString()
                + "templates" + Path.DirectorySeparatorChar.ToString() +
                "Inquiry.html";

            var subject = "new Inquiry";
            string HtmlBody = "";
            using(StreamReader sr  = System.IO.File.OpenText(PathToTemplate))
            {
                HtmlBody= sr.ReadToEnd();
            }
            /* 
            name {0}
            Email{1}
            Phone{2}
            Items{3}
            */

            StringBuilder ItemListSB = new StringBuilder();
            foreach(var item in ItemUserVM.ItemList)
            {
                ItemListSB.Append($" - Name: {item.Name} <span style='font-size:14px;'> (ID: {item.Id})</span><br />");
            }
            string messageBody = string.Format(HtmlBody,
                ItemUserVM.ApplicationUser.FullName,
                ItemUserVM.ApplicationUser.Email,
                ItemUserVM.ApplicationUser.PhoneNumber,
                ItemListSB.ToString());


            await _emailSender.SendEmailAsync(WC.EmailAdmin,subject,messageBody);


            return RedirectToAction(nameof(InquiryConfirmation));
        }



        public IActionResult InquiryConfirmation(int id)
        {
            OrderHeader orderHeader = _db.OrderHeader.FirstOrDefault(u=>u.Id == id);
            HttpContext.Session.Clear();
            return View(orderHeader);
        }




        public IActionResult Remove(int Id)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0 &&
                HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() != null)
            {
                shoppingCartList = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }

            shoppingCartList.Remove(shoppingCartList.Where(u=>u.ItemId == Id).FirstOrDefault());
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateCart(IEnumerable<Item> ItemList)
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            foreach(Item item in ItemList)
            {
                shoppingCartList.Add(new ShoppingCart { ItemId = item.Id,Kol=item.TempKol });
            }
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);

sclad/Controllers/ItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sclad.Data;
using sclad.Models;
using sclad.Models.ViewModels;

namespace sclad.Controllers
{
    [Authorize(Roles =WC.AdminRole)]
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ItemController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Item;
            foreach(var obj in objList)
            {
                obj.ItemType = _db.ItemType.FirstOrDefault(u => u.Id == obj.ItemTypeId);
                obj.Punkt = _db.Punkt.FirstOrDefault(u => u.Id == obj.PunktId);
            }
            return View(objList);
        }
        //GET-UPSERT
        public IActionResult Upsert(int? Id)
        {
            //IEnumerable<SelectListItem> ItemTypeDropDown = _db.ItemType.Select(i => new SelectListItem
            //{
            //    Text = i.Name,
            //    Value = i.Id.ToString()
            //});
            //ViewBag.ItemTypeDropDown = ItemTypeDropDown;
            //Item item = new Item();


            ItemVM itemVM = new ItemVM()
            {
                Item = new Item(),
                ItemTypeSelectLIst = _db.ItemType.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                PunktSelectLIst = _db.Punkt.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };


            if (Id == null)
            {
                //Создаем новый
                return View(itemVM);
            }
            else
            {
                itemVM.Item = _db.Item.Find(Id);
                if(itemVM.Item == null)
                {
                    return NotFound();
                }
                return View(itemVM);
            }
            
        }
        //POST-UPSERT
        [HttpPost]//Action метод типа пост дададада
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult Upsert(ItemVM itemVM)
        {
            var files = HttpContext.Request.Form.Files;
            string webRootPath = _webHostEnvironment.WebRootPath;

            if(itemVM.Item.Id == 0)
            {
                //создаем
                string upload = webRootPath + WC.ImagePath;
                string fileName = Guid.NewGuid().ToString();
                string extension = Path.GetExtension(files[0].FileName);


                using(var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                itemVM.Item.Img = fileName + extension;

                _db.Item.Add(itemVM.Item);
                TempData[WC.Success] = "Предмет создан успешно!";
            }
            else
            {
                //обновляем
                var objFromDb = _db.Item.AsNoTracking().FirstOrDefault(u=>u.Id== itemVM.Item.Id);
                if (files.Count > 0)
                {
                    string upload = webRootPath + WC.ImagePath;
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                    var oldFile= Path.Combine(upload, objFromDb.Img);

                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    itemVM.Item.Img = fileName+extension;
                }
                else
                {
                    itemVM.Item.Img = objFromDb.Img;
                }
                _db.Item.Update(itemVM.Item);
                TempData[WC.Success] = "Предмет изменён успешно!";
            }


            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET-DELETE
        public IActionResult Delete(int? Id)
        {
            if (Id == null) { return NotFound(); }
            Item item = _db.Item.Include(u => u.ItemType).Include(u => u.Punkt).FirstOrDefault(u=>u.Id==Id);
            //item.ItemType = _db.ItemType.Find(Id);
            var obj = _db.ItemType.Find(Id);
            if (item == null) { return NotFound(); }
            return View(item);
        }


        //POST-DELITE
        
        [HttpPost, ActionName("Delete")]//Action метод типа пост дададада,ну и имя для метода чтобы асп понимал как к нему лучше обращатся
        [ValidateAntiForgeryToken]//Токен от взлома
        public IActionResult DeletePost(int? Id)
        {
            var obj = _db.Item.Find(Id);
            if (obj == null) { return NotFound(); }

            string upload = _webHostEnvironment.WebRootPath + WC.ImagePath;
            var oldFile = Path.Combine(upload, obj.Img);

            if (System.IO.File.Exists(oldFile))
            {
                System.IO.File.Delete(oldFile);
            }

            _db.Item.Remove(obj);
            TempData[WC.Success] = "Предмет удалён успешно!";
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

sclad/Views/Shared/_ItemCart.cshtml
@model sclad.Models.Item
<div class="col-lg-4 col-md-6 pb-4 filter @Model.ItemType.Name.Replace(' ','_') ">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-end"><span class="text-info h5 text-end">@Model.Price@("Р/")@Model.ItemType.Unit</span></label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath@Model.Img" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush;color:black;">@Model.ItemType.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100" style="background-color:aliceblue;color:black">@Model.Punkt.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

sclad/Views/Shared/_ItemCart2.cshtml
@model sclad.Models.Item


    <tr class="filter @Model.ItemType.Name.Replace(' ','_')">
                    <td width="20%">@Model.Name</td>
                    <td width="10%">@Model.Price@("Р/")@Model.ItemType.Unit</td>
                    <td width="25%"><span class="badge p-2 border w-100" style="background-color:lavenderblush;color:black">@Model.ItemType.Name</span></td>
                    <td width="25%"><span class="badge p-2 border w-100" style="background-color:aliceblue;color:black">@Model.Punkt.Name</span></td>
                    <td class="text-center">
                    <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
                    </td>
    </tr>

sclad/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using sclad.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sclad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toastr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sclad.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css"/>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/23.1.36/fluent.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sclad</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(sclad.WC.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="NavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content menegment
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="ItemType" asp-action="Index">ItemType</a></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Punkt" asp-action="Index">Punkt</a></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Item" asp-action="Index">Item</a></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Order</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="Identity" asp-page="/Account/Register">Сreate Admin</a></li>
                                </ul>
                            </li>
                            
                        }
                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link" >
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - sclad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/23.1.36/dist/ej2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>

sclad/Views/Shared/_Notifications.cshtml
@using sclad.Utility
@if (TempData[WC.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WC.Success]');
    </script>
}
@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WC.Error]');
    </script>
}